# -*- coding: utf-8 -*-
"""거리두기_실패.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RIFjmqPTv5TPVbH9Hfhtp6BV0MAJKEkB
"""

def solution(places):
    answer = [1 for _ in range(5)]
    room = 0
    line = 0
    
    while room < 5:
        if line <5:
            for i in range(3):
                if places[room][line][i] == 'P':
                    if places[room][line][i+1] == 'P' or (line < 4 and places[room][line+1][i] == 'P'):
                        answer[room] = 0
                        room += 1
                        line = 0
                        break

                    elif (places[room][line][i+2] == 'P' and places[room][line][i+1] == 'O') or (line < 3 and places[room][line+2][i] == 'P' and places[room][line+1][i] == 'O'):
                        answer[room] = 0
                        room += 1
                        line = 0
                        break
                        
                    if line < 4 and places[room][line+1][i+1] == 'P' and (places[room][line][i+1] == 'O' or places[room][line+1][i] == 'O'):
                        answer[room] = 0
                        room += 1
                        line = 0
                        break
                        
                    if i > 0 and line < 4 and places[room][line+1][i-1] == 'P' and (places[room][line][i-1] == 'O' or places[room][line+1][i] == 'O'): 
                        answer[room] = 0
                        room += 1
                        line = 0
                        break

                if i > 0 and places[room][line][-i] == 'P':
                    if places[room][line][-i-1] == 'P' or (line < 4 and places[room][line+1][-i] == 'P'):
                        answer[room] = 0
                        room += 1
                        line = 0
                        break

                    elif (places[room][line][-i-2] == 'P' and places[room][line][-i-1] == 'O') or (line < 3 and places[room][line+2][-i] == 'P' and places[room][line+1][-i] == 'O'):
                        answer[room] = 0
                        room += 1
                        line = 0
                        break          
                        
                    if line < 4 and places[room][line+1][-i-1] == 'P' and (places[room][line][-i-1] == 'O' or places[room][line+1][-i] == 'O'):
                        answer[room] = 0
                        room += 1
                        line = 0
                        break
                        
                    if line < 4 and i == 2 and places[room][line+1][-1] == 'P' and (places[room][line][-1] == 'O' or places[room][line+1][-i] == 'O'): 
                        answer[room] = 0
                        room += 1
                        line = 0
                        break
            line += 1           
        else:
            line = 0
            room += 1
        
                
    return answer