# -*- coding: utf-8 -*-
"""오픈채팅방.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rS5fwLuOksDKgAYvJeXHzpQq5UI94PZ1
"""

def solution(record):
    
    answer = []
    user_process = {i.split()[1]: [] for i in record}
    
    for i in record:
        
        i = i.split()
        
        if i[0] == "Enter" or i[0] == "Change":
            user_process[i[1]] = i[2]
    
    for j in record:
        
        j = j.split()
        
        if j[0] == "Enter":
            
            answer.append(f"{user_process[j[1]]}님이 들어왔습니다.")
            
        elif j[0] == "Leave":
            
            answer.append(f"{user_process[j[1]]}님이 나갔습니다.")
    return answer