# -*- coding: utf-8 -*-
"""경주로_건설.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-mVX9z16HEXXkXnzg8Umh6c8ExaOqkdO
"""

def solution(board):
    visited = [[0 for _ in range(len(board))] for _ in range(len(board))]
    width = [1,0,-1,0]
    length = [0,1,0,-1]
    visited[0][0] = 1
    location = [[0,0,0,0],[0,0,0,1]] # [금액, 상-하, 좌-우, 방향결정]
    
    while location:
        check = location.pop(0)
        for direction in range(4):
            y = check[1] + length[direction]
            x = check[2] + width[direction]
            
            if x < 0 or y < 0 or x >= len(board) or y >= len(board) or board[y][x] == 1: # 끝까지 갔을 때
                continue 
                
            if direction == check[3]:             # 좌-우로 갈 수 있으면 100원 
                cost = check[0] + 100
            else:
                cost = check[0] + 600             # 아니면 600원 
                
            if visited[y][x] == 0 or cost <= visited[y][x]:        # 새로 계산한 금액이 더 적으면 바꿔주기
                visited[y][x] = cost 
                location.append([cost, y, x, direction])
                
    return visited[-1][-1]

