# -*- coding: utf-8 -*-
"""셔틀버스.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OsPt0OUgutrDY7vGUWFycGO0hXo8DRN1
"""

def solution(n, t, m, timetable):
    answer = ''
    timetable = sorted([int(time.split(':')[0])*60 +int(time.split(':')[1]) for time in timetable])
    bus = 540-t

    while n:
        bus += t
        n -= 1
        temp = [i for i in timetable if i <= bus]
        
        if len(temp) > m:      # 인원수 맞춰서 태워보내기
            temp = temp[:m]
        
        if n == 0 and len(temp) >= m:     # 막차까지 크루가 더 있으면 그 전에 탑승하기
            return "%02d:%02d"%((max(temp)-1)//60, (max(temp)-1)%60)
        
        else:
            timetable = timetable[len(temp):]      # 버스 탄 크루는 없애기
        
    return "%02d:%02d"%(bus//60, bus%60) # 버스 시간 맞춰서 가기